#!/bin/bash


# STDERR log function
err() {
    echo -e "\n[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@\n" >&2
    exit 1
}

# STDOUT log function
log() {
    echo -e "\n[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@\n"
}

if ! type "docker" > /dev/null 2>&1; then
    err "Docker not installed"
fi

if ! type "docker-compose" > /dev/null 2>&1; then
    err "Docker-Compose not installed"
fi

log "Copying .env.example -> .env"
cp src/.env.example src/.env
if [ $? -ne 0 ]; then
    err "Error while copying .env"
fi

log "Starting docker-compose stack"
docker-compose up -d
if [ $? -ne 0 ]; then
    err "Error while starting docker-compose stack."
fi

log "Installing dependencies"
docker-compose exec laravel composer install
if [ $? -ne 0 ]; then
    err "Error while installing dependencies."
fi

log "Generating app key"
docker-compose exec laravel php artisan key:generate
docker-compose exec laravel php artisan cache:clear
docker-compose exec laravel php artisan config:cache
if [ $? -ne 0 ]; then
    err "Error while generating app key."
fi

log "Running database migrations"
docker-compose exec laravel php artisan migrate --force

log "Generating JWT secret"
docker-compose exec laravel php artisan jwt:secret
if [ $? -ne 0 ]; then
    err "Error while generating JWT secret."
fi

log "Setting permissions for storage and bootstrap cache, this might ask you for your password"
sudo chmod -R 777 src/storage src/bootstrap/cache
if [ $? -ne 0 ]; then
    err "Error while setting permissions."
fi

